version: "3.8"
services:
  app:
    image: bia2002/apilaudoss-app:latest
    ports:
      - "9999:9999"
    environment:
      - MONGO_URI=mongodb://mongo:27017/laudos_db
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

